sets.exported={
    main={ name="Malevolence", augments={'INT+10','"Mag.Atk.Bns."+6',}},
    sub={ name="Malevolence", augments={'INT+4','Mag. Acc.+3','"Mag.Atk.Bns."+2','"Fast Cast"+2',}},
    range={ name="Gastraphetes", augments={'Path: A',}},
    ammo="Quelling Bolt",
    head="Malignance Chapeau",
    body="Malignance Tabard",
    hands="Malignance Gloves",
    legs="Malignance Tights",
    feet="Malignance Boots",
    neck={ name="Scout's Gorget +2", augments={'Path: A',}},
    waist="K. Kachina Belt +1",
    left_ear="Crep. Earring",
    right_ear="Telos Earring",
    left_ring="Crepuscular Ring",
    right_ring="Regal Ring",
    back=,
}