sets.exported={
    main={ name="Kumbhakarna", augments={'Pet: "Mag.Atk.Bns."+17','Pet: Phys. dmg. taken -4%','Pet: TP Bonus+180',}},
    sub={ name="Kumbhakarna", augments={'Pet: Mag. Acc.+20','Pet: TP Bonus+200',}},
    ammo="Staunch Tathlum +1",
    head="Gleti's Mask",
    body="Nukumi Gausape +2",
    hands="Totemic Gloves +3",
    legs="Gleti's Breeches",
    feet="Gleti's Boots",
    neck={ name="Bathy Choker +1", augments={'Path: A',}},
    waist="Flume Belt +1",
    left_ear="Tuisto Earring",
    right_ear={ name="Odnowa Earring +1", augments={'Path: A',}},
    left_ring="Chirich Ring +1",
    right_ring="Chirich Ring +1",
    back="Moonlight Cape",
}