sets.exported={
    main="Blurred Knife +1",
    sub="Federation Knife",
    range={ name="Anarchy", augments={'DMG:+10','Detonator:DMG:+10%',}},
    ammo="Bronze Bullet",
    head={ name="Herculean Helm", augments={'Attack+23','Weapon skill damage +4%','STR+7',}},
    body="Meg. Cuirie +2",
    hands="Chasseur's Gants +2",
    legs="Chas. Culottes +2",
    feet="Mummu Gamash. +2",
    neck={ name="Comm. Charm +1", augments={'Path: A',}},
    waist={ name="Sailfi Belt +1", augments={'Path: A',}},
    left_ear="Cessance Earring",
    right_ear="Telos Earring",
    left_ring="Chirich Ring +1",
    right_ring="Petrov Ring",
    back={ name="Camulus's Mantle", augments={'AGI+20','Mag. Acc+20 /Mag. Dmg.+20','AGI+2','Weapon skill damage +10%',}},
}