sets.exported={
    main="Blurred Knife +1",
    sub="Federation Knife",
    range={ name="Anarchy", augments={'DMG:+10','Detonator:DMG:+10%',}},
    ammo="Bronze Bullet",
    head={ name="Adhemar Bonnet +1", augments={'DEX+12','AGI+12','Accuracy+20',}},
    body={ name="Adhemar Jacket +1", augments={'DEX+12','AGI+12','Accuracy+20',}},
    hands="Chasseur's Gants +2",
    legs="Chas. Culottes +2",
    feet="Malignance Boots",
    neck="Sanctity Necklace",
    waist={ name="Sailfi Belt +1", augments={'Path: A',}},
    left_ear="Cessance Earring",
    right_ear="Telos Earring",
    left_ring="Chirich Ring +1",
    right_ring="Petrov Ring",
    back={ name="Camulus's Mantle", augments={'DEX+20','Accuracy+20 Attack+20','"Dual Wield"+10','Phys. dmg. taken-8%',}},
}